// Generated by hsmodel
package net.hearthsim.hsmodel.enum

import kotlin.String

object HSSet {
  const val BATTLEGROUNDS: String = "BATTLEGROUNDS"

  const val BLACK_TEMPLE: String = "BLACK_TEMPLE"

  const val BOOMSDAY: String = "BOOMSDAY"

  const val BRM: String = "BRM"

  const val CORE: String = "CORE"

  const val CREDITS: String = "CREDITS"

  const val DALARAN: String = "DALARAN"

  const val DARKMOON_FAIRE: String = "DARKMOON_FAIRE"

  const val DEMON_HUNTER_INITIATE: String = "DEMON_HUNTER_INITIATE"

  const val DRAGONS: String = "DRAGONS"

  const val EXPERT1: String = "EXPERT1"

  const val GANGS: String = "GANGS"

  const val GILNEAS: String = "GILNEAS"

  const val GVG: String = "GVG"

  const val HERO_SKINS: String = "HERO_SKINS"

  const val HOF: String = "HOF"

  const val ICECROWN: String = "ICECROWN"

  const val KARA: String = "KARA"

  const val LOE: String = "LOE"

  const val LOOTAPALOOZA: String = "LOOTAPALOOZA"

  const val MISSIONS: String = "MISSIONS"

  const val NAXX: String = "NAXX"

  const val OG: String = "OG"

  const val SCHOLOMANCE: String = "SCHOLOMANCE"

  const val TAVERNS_OF_TIME: String = "TAVERNS_OF_TIME"

  const val TB: String = "TB"

  const val TGT: String = "TGT"

  const val TROLL: String = "TROLL"

  const val ULDUM: String = "ULDUM"

  const val UNGORO: String = "UNGORO"

  const val WILD_EVENT: String = "WILD_EVENT"

  const val YEAR_OF_THE_DRAGON: String = "YEAR_OF_THE_DRAGON"
}
