// Generated by hsmodel
package net.hearthsim.hsmodel.enum

import kotlin.String

object Mechanic {
  const val ADJACENT_BUFF: String = "ADJACENT_BUFF"

  const val AFFECTED_BY_SPELL_POWER: String = "AFFECTED_BY_SPELL_POWER"

  const val AI_MUST_PLAY: String = "AI_MUST_PLAY"

  const val APPEAR_FUNCTIONALLY_DEAD: String = "APPEAR_FUNCTIONALLY_DEAD"

  const val AURA: String = "AURA"

  const val AUTOATTACK: String = "AUTOATTACK"

  const val BATTLECRY: String = "BATTLECRY"

  const val CANT_ATTACK: String = "CANT_ATTACK"

  const val CANT_BE_DESTROYED: String = "CANT_BE_DESTROYED"

  const val CANT_BE_FATIGUED: String = "CANT_BE_FATIGUED"

  const val CANT_BE_SILENCED: String = "CANT_BE_SILENCED"

  const val CANT_BE_TARGETED_BY_HERO_POWERS: String = "CANT_BE_TARGETED_BY_HERO_POWERS"

  const val CANT_BE_TARGETED_BY_SPELLS: String = "CANT_BE_TARGETED_BY_SPELLS"

  const val CHARGE: String = "CHARGE"

  const val CHOOSE_ONE: String = "CHOOSE_ONE"

  const val COLLECTIONMANAGER_FILTER_MANA_EVEN: String = "COLLECTIONMANAGER_FILTER_MANA_EVEN"

  const val COLLECTIONMANAGER_FILTER_MANA_ODD: String = "COLLECTIONMANAGER_FILTER_MANA_ODD"

  const val COMBO: String = "COMBO"

  const val DEATHRATTLE: String = "DEATHRATTLE"

  const val DEATH_KNIGHT: String = "DEATH_KNIGHT"

  const val DISCOVER: String = "DISCOVER"

  const val DIVINE_SHIELD: String = "DIVINE_SHIELD"

  const val DUNGEON_PASSIVE_BUFF: String = "DUNGEON_PASSIVE_BUFF"

  const val ECHO: String = "ECHO"

  const val ENCHANTMENT_INVISIBLE: String = "ENCHANTMENT_INVISIBLE"

  const val ENRAGED: String = "ENRAGED"

  const val EVIL_GLOW: String = "EVIL_GLOW"

  const val FINISH_ATTACK_SPELL_ON_DAMAGE: String = "FINISH_ATTACK_SPELL_ON_DAMAGE"

  const val FORGETFUL: String = "FORGETFUL"

  const val FREEZE: String = "FREEZE"

  const val GEARS: String = "GEARS"

  const val GHOSTLY: String = "GHOSTLY"

  const val GRIMY_GOONS: String = "GRIMY_GOONS"

  const val HEROPOWER_DAMAGE: String = "HEROPOWER_DAMAGE"

  const val IGNORE_HIDE_STATS_FOR_BIG_CARD: String = "IGNORE_HIDE_STATS_FOR_BIG_CARD"

  const val IMMUNE: String = "IMMUNE"

  const val INSPIRE: String = "INSPIRE"

  const val ImmuneToSpellpower: String = "ImmuneToSpellpower"

  const val InvisibleDeathrattle: String = "InvisibleDeathrattle"

  const val JADE_GOLEM: String = "JADE_GOLEM"

  const val JADE_LOTUS: String = "JADE_LOTUS"

  const val KABAL: String = "KABAL"

  const val LIFESTEAL: String = "LIFESTEAL"

  const val MODULAR: String = "MODULAR"

  const val MORPH: String = "MORPH"

  const val MULTIPLY_BUFF_VALUE: String = "MULTIPLY_BUFF_VALUE"

  const val OUTCAST: String = "OUTCAST"

  const val OVERKILL: String = "OVERKILL"

  const val OVERLOAD: String = "OVERLOAD"

  const val POISONOUS: String = "POISONOUS"

  const val PUZZLE: String = "PUZZLE"

  const val QUEST: String = "QUEST"

  const val REBORN: String = "REBORN"

  const val RECEIVES_DOUBLE_SPELLDAMAGE_BONUS: String = "RECEIVES_DOUBLE_SPELLDAMAGE_BONUS"

  const val RITUAL: String = "RITUAL"

  const val RUSH: String = "RUSH"

  const val SECRET: String = "SECRET"

  const val SIDEQUEST: String = "SIDEQUEST"

  const val SILENCE: String = "SILENCE"

  const val SPARE_PART: String = "SPARE_PART"

  const val SPELLPOWER: String = "SPELLPOWER"

  const val START_OF_GAME: String = "START_OF_GAME"

  const val STEALTH: String = "STEALTH"

  const val SUMMONED: String = "SUMMONED"

  const val TAG_ONE_TURN_EFFECT: String = "TAG_ONE_TURN_EFFECT"

  const val TAUNT: String = "TAUNT"

  const val TOPDECK: String = "TOPDECK"

  const val TRIGGER_VISUAL: String = "TRIGGER_VISUAL"

  const val TWINSPELL: String = "TWINSPELL"

  const val UNTOUCHABLE: String = "UNTOUCHABLE"

  const val WINDFURY: String = "WINDFURY"
}
