// Generated by hsmodel
package net.hearthsim.hsmodel.enum

import kotlin.String

object PlayerClass {
  const val DEATHKNIGHT: String = "DEATHKNIGHT"

  const val DREAM: String = "DREAM"

  const val DRUID: String = "DRUID"

  const val HUNTER: String = "HUNTER"

  const val MAGE: String = "MAGE"

  const val NEUTRAL: String = "NEUTRAL"

  const val PALADIN: String = "PALADIN"

  const val PRIEST: String = "PRIEST"

  const val ROGUE: String = "ROGUE"

  const val SHAMAN: String = "SHAMAN"

  const val WARLOCK: String = "WARLOCK"

  const val WARRIOR: String = "WARRIOR"

  const val WHIZBANG: String = "WHIZBANG"
}
