// Generated by hsmodel
package net.hearthsim.hsmodel.enum

import kotlin.String

object Race {
  const val ALL: String = "ALL"

  const val BEAST: String = "BEAST"

  const val DEMON: String = "DEMON"

  const val DRAGON: String = "DRAGON"

  const val ELEMENTAL: String = "ELEMENTAL"

  const val MECHANICAL: String = "MECHANICAL"

  const val MURLOC: String = "MURLOC"

  const val PIRATE: String = "PIRATE"

  const val TOTEM: String = "TOTEM"
}
