// Generated by hsmodel
package net.hearthsim.hsmodel.enum

import kotlin.String

object Rarity {
  const val COMMON: String = "COMMON"

  const val EPIC: String = "EPIC"

  const val FREE: String = "FREE"

  const val LEGENDARY: String = "LEGENDARY"

  const val RARE: String = "RARE"
}
