// Generated by hsmodel
package net.hearthsim.hsmodel.enum

import kotlin.String

object Type {
  const val ENCHANTMENT: String = "ENCHANTMENT"

  const val HERO: String = "HERO"

  const val HERO_POWER: String = "HERO_POWER"

  const val MINION: String = "MINION"

  const val SPELL: String = "SPELL"

  const val WEAPON: String = "WEAPON"
}
