// Generated by hsmodel
package net.mbonnin.hsmodel

object HSSet {
  const val BRM: String = "BRM"

  const val CORE: String = "CORE"

  const val CREDITS: String = "CREDITS"

  const val EXPERT1: String = "EXPERT1"

  const val GANGS: String = "GANGS"

  const val GILNEAS: String = "GILNEAS"

  const val GVG: String = "GVG"

  const val HERO_SKINS: String = "HERO_SKINS"

  const val HOF: String = "HOF"

  const val ICECROWN: String = "ICECROWN"

  const val KARA: String = "KARA"

  const val LOE: String = "LOE"

  const val LOOTAPALOOZA: String = "LOOTAPALOOZA"

  const val MISSIONS: String = "MISSIONS"

  const val NAXX: String = "NAXX"

  const val OG: String = "OG"

  const val TB: String = "TB"

  const val TGT: String = "TGT"

  const val UNGORO: String = "UNGORO"
}
