package net.mbonnin.arcanetracker

import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import org.junit.Test
import java.io.File
import java.util.*

class GenerateHsmodel {
    @Test
    fun run() {
        val hsCardList = GenerateCardData.hsCardList()

        val playerClassSet = TreeSet<String>()
        val raceSet = TreeSet<String>()
        val raritySet = TreeSet<String>()
        val setSet = TreeSet<String>()
        val typeSet = TreeSet<String>()
        val mechanicSet = TreeSet<String>()

        val map = TreeMap<String, ArrayList<String>>()
        for (card in hsCardList) {
            try {
                val cardName = card.name!!["enUS"]!!
                        .toUpperCase()
                        .replace(" ", "_")
                        .replace(Regex("[^A-Z_]"), "")

                map.getOrPut(cardName, { ArrayList() }).add(card.id)
            } catch (e: Exception) {
                //System.out.print(e)
            }

            card.cardClass?.let { playerClassSet.add(it) }
            card.race?.let { raceSet.add(it) }
            card.rarity?.let { raritySet.add(it) }
            card.set?.let { setSet.add(it) }
            card.type?.let { typeSet.add(it) }
            card.mechanics?.forEach {
                mechanicSet.add(it)
            }
        }

        val cardIds = HashMap<String, String>()
        val keys = TreeSet<String>(map.keys)
        for (key in keys) {
            val allIds = map[key]!!

            /*
             * there might be several cards with the same name (pyros is an example)
             * in that case, we sort by card id
             */
            allIds.sort()

            for ((i, id) in allIds.withIndex()) {
                var name = key
                if (i > 0) {
                    name += i
                }
                cardIds.put(name, id)
            }
        }


        val outputDir = File(Constant.HSMODEL_SRC_MAIN_JAVA_PATH)
        generateFile("CardId", cardIds, outputDir)

        generateEnumFile("PlayerClass", playerClassSet, outputDir)
        generateEnumFile("Race", raceSet, outputDir)
        generateEnumFile("Rarity", raritySet, outputDir)
        generateEnumFile("HSSet", setSet, outputDir)
        generateEnumFile("Mechanic", mechanicSet, outputDir)
        generateEnumFile("Type", typeSet, outputDir)
    }

    companion object {
        private fun generateEnumFile(fileName: String, propertySet: Set<String>, outputDir: File) {
            generateFile(fileName, propertySet.map { it to it }.toMap(), outputDir)
        }

        private fun generateFile(fileName: String, properties: Map<String, String>, outputDir: File) {
            val fileBuilder = FileSpec.builder("net.mbonnin.hsmodel", fileName)
            fileBuilder.addComment("Generated by hsmodel")

            val typeBuilder = TypeSpec.objectBuilder(fileName)
            for (property in properties) {
                typeBuilder.addProperty(PropertySpec.builder(property.key, String::class)
                        .initializer("\"" + property.value + "\"")
                        .addModifiers(KModifier.CONST, KModifier.PUBLIC)
                        .mutable(false)
                        .build())
            }
            fileBuilder.addType(typeBuilder.build())

            fileBuilder.build().writeTo(outputDir)
        }
    }
}